### ISSUE TITLE
Outdated extension for vscode

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-devbox#100]
[This extension is quite outdated](https://github.com/jhipster/jhipster-devbox/blob/9dfbe374c95e562e890edcafd8252e05ff4730bb/tools/visual-studio-code-extensions.sh#L16)... you may want to use the [official extension](https://marketplace.visualstudio.com/items?itemName=jhipster-ide.jdl)?

**Comment by pascalgrimaud** [comment]
yes ! we should use the official one.
Can you PR ?

But not sure if Julien solves the issue with Devbox for JHipster v5.7.0

**Comment by jdubois** [comment]
Yes we need to upgrade, I didn't know this, thanks @colameo if you can do a PR
And yes @pascalgrimaud I fixed the devbox, but I do a system update so the build isn't reproductible

**Comment by colameo** [comment]
[see pr 101](https://github.com/jhipster/jhipster-devbox/pull/101).
Shall we add atom to devbox as well?

**Comment by pascalgrimaud** [comment]
@colameo : we already added VSCode to devbox so I don't think it's a good idea to add both by default.

**Comment by colameo** [comment]
ok fine. btw, this devbox could be made available (integrated) in the jhipster ide as feature. But don't know if it's worth ...

**Comment by colameo** [comment]
...what I mean is, that by installing the jh ide developers would be able to run the devbox inside the ide (for the moment I would limit this feature to eclipse users only). ... but, but, we have more important features to provide than this ... so let's keep it in mind for the future  ;-)

**Comment by pascalgrimaud** [comment]
@jdubois : FYI, I tested the devbox yesterday and it works well !

**Comment by jdubois** [comment]
Thanks!!
