### ISSUE TITLE
docker-compose install finds no valid binary in last 4 found instances ( curl: (3) <url> malformed )

### ISSUE THREAD

**Issue by dhamann** [jhipster/jhipster-devbox#121]
Hi there,

i just installed the jhipster-devbox and after running through vagrant up i was not able to use docker-compose.

After a bit of digging i found out that in the following line  ... when i changed the "**head -n 4**" to "**head -n 8**" a valid binary was found again in the grepped lines.

https://github.com/jhipster/jhipster-devbox/blob/54980c3704424cb2c3b0783b5322b741a4833295/scripts/setup.sh#L128

Hope that helps someone trying to run mysql inside devbox for example \o/

cheers

(and for the sake of search engine fu: curl: (3) <url> malformed is what it states when you call the cited line unedited)

**Comment by pascalgrimaud** [comment]
@dhamann : would you like to contribute to this project and propose your fix plz ?

**Comment by dhamann** [comment]
@pascalgrimaud i was not proposing anything as i was not sure if my proposed solution would suffice. 

and actually after thinking about the way the greps are chained my solution now is a different one.

i would think it might be less brittle to first "grep for Linux" then "remove the sha256" and after that "reduce via head -n 1"

see #122

**Comment by pascalgrimaud** [comment]
I think it resolved the issue
Just tried it and the new `curl` command works well. The older was broken.

Thanks a lot @dhamann 
I'm closing this as https://github.com/jhipster/jhipster-devbox/pull/122 has been merged
