### ISSUE TITLE
Deploy the devbox to Atlas

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-devbox#14]
To make the box available on https://atlas.hashicorp.com/ from @cbornet 

Vagrant up to start and provision the vm
Then in the vm (or by vagrant ssh) to reduce the box size :
 * sudo apt-get clean
 * sudo dd if=/dev/zero of=/EMPTY bs=1M && sudo rm -f /EMPTY
 * cat /dev/null > ~/.bash_history && history -c
(these commands could be added to the setup script)
Then "vagrant package" to package in a .box file
Then upload your box in https://atlas.hashicorp.com/boxes/new

**Comment by jdubois** [comment]
@cbornet I'm going to try to deploy it to the JHipster organization on Atlas -> if you have time to add the clean up scripts to the setup.sh, I'd merge them

**Comment by jdubois** [comment]
It should be live at https://atlas.hashicorp.com/jhipster/boxes/jhipster-devbox -> but this needs to be tested first!

**Comment by cbornet** [comment]
Cool ! Now I can use it as seed for my own box :+1:

**Comment by jdubois** [comment]
Just tested it, the GUI isn't working :-(
@cbornet if you have any hints...

**Comment by cbornet** [comment]
Did you set ```vb.gui = true``` in the Vagrantfile that pulls the box ?

**Comment by jdubois** [comment]
@cbornet yes it's the one from this project... I've done a new version, I'll deploy it as v0.2.1 when it's ready

**Comment by cbornet** [comment]
Note that you can test your packaged box locally before pushing
```shell
vagrant box add jhipster-devbox-local jhipster-devbox.box
```
Then in the Vagrantfile
```ruby
config.vm.box = "jhipster-devbox-local"
```

**Comment by cbornet** [comment]
Oh I see ! ```sudo dd if=/dev/zero of=/EMPTY bs=1M``` terminates with an error when the disk if full.
So ```sudo rm -f /EMPTY``` is not executed, the disk is full, and nothing works anymore ...
If you remove /EMPTY from the console, then the gui starts again. It also seems some SW were not installed (eg. guake)

**Comment by jdubois** [comment]
OK, I removed those: the file is much bigger but it looks like it's working! Can you test it? It's version 0.2.1 (the only one currently released)

**Comment by cbornet** [comment]
Works OK but it seems heroku, mysql and chrome were not installed. Is it on purpose ?

**Comment by jdubois** [comment]
Good news, at least I can deploy to Atlas!
No there is an installation problem: I also had to add Guake manually, and do an apt-get update manually -> we have something totally broken in the setup.sh script, and I don't know what or why (it was working a couple of days ago, so maybe something we merged?)

**Comment by jdubois** [comment]
OK the issue comes from downloading the .m2 repo (that was added by @pascalgrimaud ). I have no idea why, but after checking out the Github repo, the build stops, and that's why the VM doesn't have everything installed

**Comment by pascalgrimaud** [comment]
Oh sorry, maybe the repo is too big? I ll have a look this weekend

**Comment by jdubois** [comment]
@pascalgrimaud I'm really not sure what the error is...

**Comment by jdubois** [comment]
OK I did a new box, uploaded it, and it looks like it's working!
So maybe I had a network issue when I created the previous box.
