### ISSUE TITLE
Add STS to PATH

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#17]
Or create an alias so that STS can easily be started from a terminal

**Comment by pascalgrimaud** [comment]
there is a shortcut in desktop.
Isn't it enough ?

**Comment by cbornet** [comment]
Well some people don't use the Desktop that much ;-)

**Comment by jdubois** [comment]
Well, for STS you're supposed to use a Desktop :-)

Anyway, yes it would be nice to have, I guess it's just adding a line to the .bash_profile?
