### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by alfredorueda** [jhipster/jhipster-devbox#18]
I am trying to use the latest version ( Upgrade to JHipster 2.25.0) but I have encountered the following problem:

![image](https://cloud.githubusercontent.com/assets/8808034/11609892/f2318a46-9b92-11e5-841c-f35b620de069.png)

Windows 8.1
Vagrant 1.7.3 (with Vagrant 1.7.4 fails even when trying to download the image). 

I suppose it's a configuration problem in my windows environment  or a Vagrant bug. I will post the solution to help other users.

Thanks for your support!

**Comment by johnsgp** [comment]
Guided by https://github.com/jhipster/jhipster-devbox/issues/16, after running 'vagrant init jhipster/jhipster-devbox', I added

    config.ssh.insert_key = false

to the Vagrantfile immediately after

    config.vm.box = "jhipster/jhipster-devbox"

This allowed 'vagrant up --provider virtualbox' to start properly and I can ssh onto the box.  I'm not sure whether this is a valid solution or not.

**Comment by jdubois** [comment]
I'd be happy to do this change, but I don't know Vagrant enough to be sure if that's a good idea or not... Do you have any Vagrant documentation on this?

**Comment by cbornet** [comment]
See https://docs.vagrantup.com/v2/boxes/base.html at "vagrant User":
"By default, Vagrant expects a "vagrant" user to SSH into the machine as. This user should be setup with the insecure keypair that Vagrant uses as a default to attempt to SSH.[...]When Vagrant boots a box and detects the insecure keypair, it will automatically replace it with a randomly generated keypair for additional security while the box is running."

At the moment, every jhipster-devbox has the same ssh key pair when up whiwh is a security issue !

**Comment by jdubois** [comment]
OK, let me try that. I'm just generating the next box for 2.26.0....

**Comment by cbornet** [comment]
The thing is : for people who clone from github, they should set the insert_key to true to have their key pair changed.

**Comment by jdubois** [comment]
@cbornet I'm not sure I understand this correctly....

- It should be set to "true" for people cloning, so they have their own key -> OK
- It should be set to "false" for people getting the box from Atlas, so everybody doesn't use the same key -> I understand the security issue, then that's just the devbox and it's running on your computer, so I'm sure there is an issue here (the ssh port is not forwarded)

Then why is there this issue here? It was better with "true"

**Comment by jdubois** [comment]
After some testing: I need this to "true" for myself (for building) and for people cloning the repo (like in this ticket).

I understand this can be a security issue as the key is public, but once again this is just a VM, and your host should not forward this port anyway, so I don't think this should be an error.

We could write a warning in the README, of course, but now I'm putting this back to "true"

**Comment by cbornet** [comment]
@jdubois I'm coming back on this after some time. I think we can leave the insert_key to true in git for people that clone the devbox.
But when you create the box for packaging to Atlas, can you be sure to set it to false so that the default ssl key is not replaced ?

**Comment by jdubois** [comment]
@cbornet the problem is that I only have one box for everything :-)
I need to check how this could be changed.

**Comment by cbornet** [comment]
Maybe changing back the key manually before packaging in authorized_keys
The insecure public key is:
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
```

**Comment by jdubois** [comment]
You mean just deleting it from the `.ssh` directory? Would that cause any issue?

**Comment by cbornet** [comment]
I mean replacing the public key that was changed when you up'ed the box the first time by this one. I don't know if it will work.
Why is it a problem to set ```config.ssh.insert_key = false``` to the Vagrantfile you use for packaging (only yours, without commiting to git) ?
