### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#2]
This is because of
```
config.vm.synced_folder "~/jhipster", "/home/vagrant/jhipster"
```
Windows can't find ~/jhipster (obviously)

**Comment by cbornet** [comment]
Also it seems that the dir will not be created if doesn't exist so it must be created before launching vagrant up

**Comment by jdubois** [comment]
Yes, this is annoying, I'll remove the shared directory

**Comment by cbornet** [comment]
Can we just comment it ? Or indicate in README how to setup the shared folder ?

**Comment by jdubois** [comment]
At the moment I am not using it anyway, so this isn't important

**Comment by cbornet** [comment]
Note that the dir containing the Vagrantfile is synced by default with ```/vagrant``` so another synced dir may not be needed
