### ISSUE TITLE
Create a devbox for yeoman generator developer

### ISSUE THREAD

**Issue by wuethrich44** [jhipster/jhipster-devbox#23]
As far as I understand this devbox is for developers which work with the generated application. Is there any interest in a devbox for developers which work on the yeoman generator. This devbox could have the following features:

* Atom-Editor
* Cloned jhipster-generator repo
* All sample apps cloned
* All SDK for the deployment subgen installed

What are your opinions about that?

**Comment by pascalgrimaud** [comment]
I think you can already use this devbox for this => jdk, node, npm, bower, grunt, atom, etc.

Clone the original jhipster-generator is not a good idea, because you should clone your fork instead, and add remote upstream, then npm link

**Comment by jdubois** [comment]
Yes, the devbox is probably already good for developping JHipster itself, just clone your fork, and all the tools are already there!

**Comment by cbornet** [comment]
Btw, you can create your own devbox based on the jhipster own (that's what I did for my team)

**Comment by wuethrich44** [comment]
@cbornet Thanks for the tip I will do that
