### ISSUE TITLE
Remove sudo from installation script

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#26]
As the script is already run as sudo by vagrant

**Comment by PierreBesson** [comment]
Did you test this ?

**Comment by cbornet** [comment]
I did it on my vagrant box which is derived from jhipter-devbox and it worked well. I didn't test on the jhipster-devbox itself though
See https://www.vagrantup.com/docs/provisioning/shell.html#privileged

**Comment by PierreBesson** [comment]
In this case I will remove them tomorrow if @jdubois agrees.
Do you have other features in your own devbox that could be useful for us ?

Le mar. 8 mars 2016 18:54, Christophe Bornet <notifications@github.com> a
écrit :

**Comment by cbornet** [comment]
I had added docker docker-compose and jhipster-uml. I guess this is not needed anymore :smile:
