### ISSUE TITLE
MySQL / MySQL Workbench not installed

### ISSUE THREAD

**Issue by jordanbaucke** [jhipster/jhipster-devbox#30]
I ran the vagrant installer from Atlas and MySQL / MySQL Workbench were not installed by default.

**Comment by PierreBesson** [comment]
This has been removed in the last version as the recommended way is to launch mysql with `docker-compose -f src/main/docker/mysql.yml up -d` 
(see https://github.com/jhipster/jhipster-devbox/pull/25).

**Comment by jordanbaucke** [comment]
@PierreBesson thanks! Is this documented so I can follow?

**Comment by PierreBesson** [comment]
Glad you found the docs ! :smile:.
If you really need the workbench, you can install it by yourself using apt-get.

**Comment by jordanbaucke** [comment]
@PierreBesson cheers! Already done. This maybe a naive question but if I'm working on my app in Vagrant VM should I installed Docker composer there and launch the Docker containers from within the VM or install on host machine? I guess it doesn't matter except for NAT - but I'm not seeing docker-composer installed either so I was hesitant.

**Comment by PierreBesson** [comment]
docker-compose should be installed installed in the VM. If it is not it's a bug.

**Comment by jordanbaucke** [comment]
Hmmm, so I'm seeing this in a fresh devbox.

![2016-04-08_10-14-59](https://cloud.githubusercontent.com/assets/354791/14391752/d0a74e96-fd72-11e5-8ff9-a80ccba36268.png)

**Comment by pascalgrimaud** [comment]
It's docker-compose, not docker-composer

**Comment by jordanbaucke** [comment]
@pascalgrimaud ::facepalm:: thank you for your help!

**Comment by jdubois** [comment]
Yes for MySQL -> all servers are now installed through Docker
But for MySQL Workbench that's different, it should have been installed, I will add it to the build script for the next release.
