### ISSUE TITLE
Migrate from STS to IDEA Community Edition

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-devbox#31]
I just completed a training and we had so many issues with STS.... I use IDEA Ultimate Edition, but the Community Edition is free and enough to work on a normal JHipster project.
So my proposal is to migrate to IDEA Community Edition in the devbox.

**Comment by pascalgrimaud** [comment]
Previous versions shouldn't change their link:
https://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases

And I think older version of IntelliJ should be better than STS :dancers:

**Comment by jdubois** [comment]
Good catch!! In that case let's use an older version, indeed.

**Comment by pascalgrimaud** [comment]
sorry, I can't PR => my connexion at home sux so much, so I can't test before PR

**Comment by jdubois** [comment]
@pascalgrimaud no problem, I have the code ready but haven't pushed yet, so don't bother doing it!

**Comment by jdubois** [comment]
I think I have a better solution -> https://wiki.ubuntu.com/ubuntu-make

**Comment by pascalgrimaud** [comment]
if it can work, let's try this !

**Comment by jdubois** [comment]
I have Ubuntu Make working with my latest commit, can you have a look?
I couldn't do the automatic installation, so you need to run "umake ide idea"

**Comment by cbornet** [comment]
umake ide visual-studio-code :+1:
