### ISSUE TITLE
Upgrade to Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#33]

**Comment by pascalgrimaud** [comment]
To be sync, we should upgrade our [JHipster Docker image](https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile) too with ubuntu:xenial

**Comment by PierreBesson** [comment]
I will take care of it. Both for the docker image and the devbox.

**Comment by PierreBesson** [comment]
However for 16.04, I don't think it's needed to use the webupd8team java version anymore (oracle java) as the openjdk provided by ubuntu will be java 8.

**Comment by PierreBesson** [comment]
Once the upgrade to 16.04 is done we should also do the 3.1.0 release of the devbox.

**Comment by jdubois** [comment]
Oh yes let's use OpenJDK here too, so we have the same JVM for Docker and the Devbox.

**Comment by PierreBesson** [comment]
@pascalgrimaud, I have upgraded the docker image to ubuntu/xenial ([here](https://github.com/PierreBesson/generator-jhipster/blob/upgrade-docker-ubuntu-xenial/Dockerfile)) but when I test it, I have an issue with node:

```
   create bower.json
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/jhipster/app/bower.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at write (/usr/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/commit.js:14:6)
    at DestroyableTransform._transform (/usr/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/commit.js:43:7)
    at DestroyableTransform.Transform._read (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/usr/lib/node_modules/generator-jhipster/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)

```

Also the sudo command doesn't work properly in the container.

**Comment by pascalgrimaud** [comment]
How did you test the image?
Did you create the folder before launching the container+volume?

**Comment by PierreBesson** [comment]
Yes I did create the folder.
I just did a docker build . in the main generator then run the resulting image following the docs instructions.

**Comment by pascalgrimaud** [comment]
I will have a look this weekend

**Comment by pascalgrimaud** [comment]
@PierreBesson : I build your Dockerfile into `jhipster/jhipster:pbesson`, with minor modification: `ENV JAVA_HOME /usr/lib/jvm/java-${JAVA_VERSION}-openjdk-amd64`

Then, I type these commands:
```shell
pgrimaud@pgrimaud:~/workspace/tests$ mkdir 05-docker
pgrimaud@pgrimaud:~/workspace/tests$ cd 05-docker/
pgrimaud@pgrimaud:~/workspace/tests/05-docker$ docker run --name jhipster -d -p 8080:8080 -v $(pwd):/home/jhipster/app -t jhipster/jhipster:pbesson
ac0cf180cc909a5336ef18216b8bdb6e102f047c104c334f6ee466c147760438
pgrimaud@pgrimaud:~/workspace/tests/05-docker$ docker exec -it jhipster bash
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

jhipster@ac0cf180cc90:~/app$ ls -l /home/jhipster/
total 8
drwxrwxr-x  2 jhipster jhipster 4096 Apr 30 19:36 app
drwxr-xr-x 14 jhipster jhipster 4096 Apr 30 19:33 generator-jhipster
jhipster@ac0cf180cc90:~/app$ yo jhipster
```

I don't have any problem, the application is generated.

**Comment by cbornet** [comment]
I have tried to build the box from ubuntu/xenial64 but it failed because the base box didn't have any vagrant user.
Can someone else confirm this ?

**Comment by jdubois** [comment]
Hey I'm doing the same thing :-)
Indeed there is no Vagrant user, so I'm re-using the script I did for my trainings, with a JHipster user.

I'll commit it when I see it works, for the record the line is:

`useradd jhipster --password xTZgpKFPrv2fA --home /home/jhipster --create-home`

**Comment by cbornet** [comment]
Ok. Then I let you do it :-)

**Comment by jdubois** [comment]
I just commited my changes -> can you have a look?

**Comment by PierreBesson** [comment]
Oh yeah, I had the same problems when I tried to do it a few days ago. I'm not sure if adding a user will fix the problem as I couldn't even reach a graphical login screen last time.

**Comment by jdubois** [comment]
Oh it's working, that's for sure!

**Comment by PierreBesson** [comment]
Great !
