### ISSUE TITLE
Switch to xubuntu

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-devbox#35]
- At all my trainings people have trouble using Ubuntu Desktop
- XUbuntu is lighter, so I hope it will work faster

**Comment by cbornet** [comment]
As for ubuntu desktop, I think it's because the 3D acceleration is not enabled. You need to install the vbox-extensions.

**Comment by jdubois** [comment]
No it's installed and it's working, it's just the way it works that confuses users. And I expect it to be slower, also.

**Comment by cbornet** [comment]
Just tested the latest box with xenial and xubuntu and it's indeed much faster.
Can't wait or the official release !
