### ISSUE TITLE
Default language is setted to french 

### ISSUE THREAD

**Issue by ningod** [jhipster/jhipster-devbox#39]
After log in into the VM by Virtual Box interface, system (xubuntu) is by default in french language, also the home folders are localized in french ( i.e. Desktop -> Bureau )
My host system is in English

![image](https://cloud.githubusercontent.com/assets/3158953/15146734/443c0140-16bd-11e6-950b-4c20fe3b0856.png)

**Comment by jdubois** [comment]
I think it takes the language of the person who generates the image.

- this probably isn't an issue if you build the image yourself
- for the Atlas image, I guess the only solution is me setting up manually English after image build -> I'm going to do this right now, and do a new release

**Comment by cbornet** [comment]
English is not even proposed in settings. I think the xenial image doesn't have it.
```
apt-get install -y language-pack-en
```
did it for me

**Comment by jdubois** [comment]
I just released a new v3.2.1.2 version on Atlas, which should solve this problem as I changed the language manually.
@cbornet I'm also adding this line to the build and testing

**Comment by ningod** [comment]
the problem is not completly resolved.

![image](https://cloud.githubusercontent.com/assets/3158953/15183050/bd3ec37a-178f-11e6-8a72-f300bea00a88.png)

**Comment by jdubois** [comment]
thanks! this box is so broken we are going to switch back to Trusty cc @jhipster/developers 

I'm going to add a new ticket for this switch and close the "Xenial" tickets...
