### ISSUE TITLE
Issue when generating project with linked generator

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#40]
I have errors when generating a project after linking to my cloned generator-jhipster

Steps to reproduce:
* login as jhipster
* clone generator-jhipster
* sudo npm link
* create a new project
* yo jhipster
--> error

I think is because the node_modules inside /usr/lib belong to the ubuntu group (as they were pulled by the ubuntu user during box generation)
If I change ownership to jhipster, then it works again.

It's really a pain that the ubuntu box doesn't respect the vagrant user requirement...

**Comment by jdubois** [comment]
Very annoying....
I'll do:
    sudo chown -R jhipster $(npm config get prefix)/{lib/node_modules,bin,share}
