### ISSUE TITLE
Disk too small

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#42]
The previous ubuntu image had a 40G disk. The new one has only 10G and its already almost full when you first start it.
I often have a lot of disk/FS errors when starting the VM (in that case I need to restart it completely) and I suspect it is due to this.

**Comment by jdubois** [comment]
I can't find a good solution to this....
Shouldn't we go back to Ubuntu 14???

**Comment by cbornet** [comment]
>I can't find a good solution to this....
Yes, resizing the disk is a painful process and I don't see how to automate it
>Shouldn't we go back to Ubuntu 14???
That's also what I'm thinking. The xenial box isn't mature enough I'm afraid... It looks like a simple packaging of the ubuntu cloud image without the necessary changes to make it a vagrant base box.

**Comment by jdubois** [comment]
@jhipster/developers I think we should go back to using the older Ubuntu 14 for our devbox, as the new "Xenial" release is very badly packaged

**Comment by cbornet** [comment]
What we could do is create an alternate xenial box that just have the vagrant user configured and the disk upped to 40GB. Then we should not upgrade that box that often.

**Comment by pascalgrimaud** [comment]
Lot of new issues and lot of work since the "Xenial" release
So yes, maybe we have to think about going back to "Trusty", no objection for me

**Comment by jdubois** [comment]
Closed as we will switch back to Trusty - see #43
