### ISSUE TITLE
Switch back to Ubuntu Trusty

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-devbox#43]
We've had so many bugs with Ubuntu Xenial, let's switch back to Trusty.

**Comment by pascalgrimaud** [comment]
@jdubois : I don't see any issues with our [Xenial Dockerfile](https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile).
So will we only revert back the Devbox ?

cc @PierreBesson

**Comment by jdubois** [comment]
Yes most of the issues we have are specific to Vagrant, or to the GUI.... so they won't affect our Docker build.
Then, it's probably wiser to have the same version everywhere.

**Comment by PierreBesson** [comment]
I'm against reverting the Dockerfile to Trusty as we wouldn't be able use openjdk from the official repository (limited to openjdk 7 in trusty).

Really our issues are vagrant specific and they can be worked out.

**Comment by jdubois** [comment]
Yes I'm just seeing this at the moment on the devbox, I had to switch to Oracle JDK, and this is very bad.
So let's keep the Docker build on Xenial

**Comment by cbornet** [comment]
So what would you think of doing an intermediate box that is a fixed xenial64 box ?

**Comment by jdubois** [comment]
I think that's a lot of work and that I've lost enough time with the devbox... Let's switch back to Ubuntu Trusty, it was working well.

**Comment by cbornet** [comment]
Can we keep xubuntu ?

**Comment by cbornet** [comment]
Or at least gnome-session-flashback

**Comment by jdubois** [comment]
I was having errors with Xubuntu.... But yes it would be my favorite
solution.
Le 11 mai 2016 6:31 PM, "Christophe Bornet" <notifications@github.com> a
écrit :

**Comment by cbornet** [comment]
What errors did you get ? I didn't have any issue...

**Comment by jdubois** [comment]
- after login to Xubuntu, I get 2 error messages -> they can be ignored but still it's a bad first impression
- I had issues with 3D acceleration -> might be my fault, i would need more time to test
- I had issue with having French as default language -> 99% chances this is my fault, but still I need time test

So in the end I sure think we should move to Xubuntu, but it takes a long time to test, and I've already spent too much time on the DevBox.
If you have the time and are sure it works OK, I'm trusting you, of course!

**Comment by cbornet** [comment]
My connection is too bad at the moment to test the devbox. I'll do it tonight at home.
* Yes, I also got the error messages. But I think I also got them with ubuntu-desktop
* I think this is because the vbox extensions were missing on Xenial (yet another issue). Can you test on Trusty ?
* I think it was because french was installed before english on Xenial. Can you test on Trusty ?

**Comment by jdubois** [comment]
I merged your PR... So we'll soon find out if it works or not!
