### ISSUE TITLE
Forward more ports for micro services

### ISSUE THREAD

**Issue by gmarziou** [jhipster/jhipster-devbox#51]
The current configuration forwards only ports 8080 and 9000 which are the default ones for working on a monolith app, shouldn't we make it easier for micro services apps too by including port ranges like below?

``` ruby
# JHipster registry default port
config.vm.network :forwarded_port, guest: 8761, host: 8761
# Spring boot ports
for p in 8080..8090
    config.vm.network :forwarded_port, guest: p, host: p
end
# browser-sync ports
for p in 9000..9010
    config.vm.network :forwarded_port, guest: p, host: p
end
```

**Comment by jdubois** [comment]
Maybe in dev, but definitely not in prod.
The issue we only have one configuration.

**Comment by gmarziou** [comment]
I was misleading by **dev**box name ;)

**Comment by jdubois** [comment]
Sorry I should stop answering this with my phone :-)

**Comment by jdubois** [comment]
So to answer you correctly: yes I agree it's a good idea

**Comment by jdubois** [comment]
@gmarziou can you a PR with those changes?

**Comment by gmarziou** [comment]
OK, I will

**Comment by jdubois** [comment]
No news from a long time, I guess this isn't that important :-)
