### ISSUE TITLE
Add Kitematic

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-devbox#53]
It would be useful to have Kitematic in the devbox as it can now be packaged as a .deb (see [this kitematic PR](https://github.com/docker/kitematic/pull/1677)).

The only problem is that we have to build the .deb ourself, I don't see it being distributed by Docker any time soon as the Linux support is community contributed.

To try it:
```
curl -O https://github.com/PierreBesson/jhipster-devbox/blob/install-kitematic/packages/Kitematic_0.10.2-1_amd64.deb
sudo dpkg -i dist/Kitematic_0.10.2-1_amd64.deb
```

**Comment by FrenchBen** [comment]
@PierreBesson Since we do have the 'release' versions available, I'm sure they can be made downloadable from the release tab.

**Comment by PierreBesson** [comment]
@FrenchBen Great, then we will wait for the deb package to be available from the github release tab.
