### ISSUE TITLE
Not able to login after system is locked.

### ISSUE THREAD

**Issue by RawSanj** [jhipster/jhipster-devbox#54]
**Version : 3.3.0**

**Host OS: Windows 10**

**Issue:** Not able to login with username and password as *vagrant*.

I can only login when I boot and if system gets locked, the password *vagrant* doesn't unlock the system.
Screen flashes and settles down to Locked screen.

PS: It does not give password error. *vagrant* is correct password but can't unlock system with it.

**Comment by cbornet** [comment]
Also happened to me so I deactivated the vm screen lock (the host already locks so that's fine)

**Comment by RawSanj** [comment]
Apart from this, many links/button doesn't work such as About this computer, System settings, etc on top right.
