### ISSUE TITLE
Consider using bento ubuntu-16.04-amd64

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#57]
See https://atlas.hashicorp.com/kaorimatz/boxes/ubuntu-16.04-amd64
The template used is in https://github.com/kaorimatz/packer-templates/blob/master/ubuntu-16.04-amd64.json so we can see exactly what was used to generate.

**Comment by jdubois** [comment]
I'd rather use the official images, and not go into validating what kaorimatz is doing. I'm pretty happy with the current box, even if it's not the latest Ubuntu version (and I don't care about it that much...).

**Comment by cbornet** [comment]
OK.
FYI, I also found the box that is used by the chef team : https://github.com/chef/bento which seem very well maintained.
https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04
