### ISSUE TITLE
Install VSCode

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#60]
Since everybody likes VSCode, we should install it instead of Atom (very easy vith ubuntu-make)
What extensions would you like to see installed ?

**Comment by jdubois** [comment]
Yeoman (which is broken at the moment) and the Java support by RedHat.

The documentation for the website is ready, I'm just waiting for our next minor release to publish it.

**Comment by cbornet** [comment]
OK. I have also in mind ESLint (or TSLint ?) , Angular 1 and 2 Typescript Snippets, GitHistory, EditorConfig

**Comment by PierreBesson** [comment]
Maybe we should setup the vscode workspace ([.vscode/settings.json](https://code.visualstudio.com/docs/customization/userandworkspace)) and chrome debugger ([.vscode/launch.json](https://github.com/Microsoft/vscode-chrome-debug)).

**Comment by cbornet** [comment]
Note : VS code crashes on Virtualbox > 5.0.16 + 3D acceleration.
To prevent that, I have to start it with ```code --disable-gpu```. Maybe we could set the --disable-gpu in the start script.

**Comment by jdubois** [comment]
Yes but isn't GPU important? I'd rather keep it than have VS Code at the moment. Intellij Community is very good for our current use case (it will change with AngularJS 2, but that's not the time yet)

**Comment by cbornet** [comment]
It doesn't disable the GPU globally: it's only for VS Code

**Comment by jdubois** [comment]
Oh sorry, I thought it was in VirtualBox! No problem, then.
