### ISSUE TITLE
Run box with a specific jhipster version

### ISSUE THREAD

**Issue by lrkwz** [jhipster/jhipster-devbox#65]
Sorry I'm a vagrant newby, is there a way to run the box for a specific jhipster version?

Thank you

**Comment by jdubois** [comment]
You can install another JHipster version using "npm install".

**Comment by lrkwz** [comment]
I meant a complete vagrant box.

You suggestion is:

- run the last vargant box
- downgrade to the needed jhipster

right?

**Comment by jdubois** [comment]
Yes, you take the latest box, and use "npm install" to install another JHipster version.

Other solution is to take the Vagrant box which is linked to the JHipster you want: they have the same version number, for that purpose.

**Comment by lrkwz** [comment]
I would prefere the "other solution" but how do I do it?
The list on [atlas](https://atlas.hashicorp.com/jhipster/boxes/jhipster-devbox) states

> There is not currently a released version.

for all versions except the last one.

**Comment by jdubois** [comment]
I haven't seen that yet, and to be honest I've never used it (I'm doing the images, so I don't need to....). Can't you do a "vagrant init" and specify the version number?
