### ISSUE TITLE
Installation of Visual Studio code fails

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-devbox#69]
That's not very important for me -> we should have this through Ubuntu Make, maybe this should be totally removed in fact?
But notifying @cbornet as he coded it.

**Comment by cbornet** [comment]
I'll have a look

**Comment by cbornet** [comment]
Do you have the error log ?

**Comment by jdubois** [comment]
Sorry I didn't keep the error log.... But just do a "vagrant up" and you will see it.
