### ISSUE TITLE
How is zsh setup as default shell for vagrant account ?

### ISSUE THREAD

**Issue by kbjp** [jhipster/jhipster-devbox#73]
Hi,
Apologies for the rookie Unix/Linux question but why is it the vagrant account ends up with zsh as its default shell when bash is listed as the default choice for that user in /etc/passwd ?
Thank you very much in advance for your patience.
Regards
kbjp

**Comment by pascalgrimaud** [comment]
Hello @kbjp 

With these line:
https://github.com/jhipster/jhipster-devbox/blob/master/scripts/setup.sh#L119-L123

And there is a PR to make it as default shell with guake too: https://github.com/jhipster/jhipster-devbox/pull/66

**Comment by kbjp** [comment]
Thanks a lot for taking time to reply !
