### ISSUE TITLE
Not compatible with Docker for Windows

### ISSUE THREAD

**Issue by gavvvr** [jhipster/jhipster-devbox#75]
I have windows 10 installed on my machine and used to this Vagrant image for Java developing.

Recently i installed Docker for Windows which uses Hyper-V and can't use virtualbox anymore. Thus this Vagrant image is also unavailable for me. 
I would like to use Docker for Windows and this Vagrant image simultaneously, which is impossible with VirtualBox provider.

I saw in documentation that Docker can be used as vagrant provider, but this image is built for VBox. 
I suggest to support Docker provider for this image if it is possible.

**Comment by PierreBesson** [comment]
@gavvvr I really doubt this is feasible as our devbox is a graphical environment and docker is not intended to support those. How would you display the X server in windows ?

**Comment by PierreBesson** [comment]
@gavvvr You might want to have a look to our JHipster docker image, instructions are on our website, it will work in docker for windows and might be what you are looking for.

**Comment by jdubois** [comment]
I'm sorry I don't understand the discussion:

- There is indeed Docker working on this image, so you shouldn't have any issue
- If you want to use Docker 4 Windows, I don't understand why this would prevent you from using Vagrant?? Or there's a huge bug with Docker 4 Windows, and that's not our fault

**Comment by jdubois** [comment]
Oh sorry, you want to run this image inside Docker 4 Windows? I don't think that could work, there's a whole GUI here, that's not how you're supposed to use Docker

**Comment by gavvvr** [comment]
@jdubois maybe you can make Vagrant image which supports `hyperv` provider?
I just want to use both Docker for Windows and jhipster Vagrant image on my Windows 10 host PC.

**Comment by jdubois** [comment]
Yes it's only a VirtualBox image - I don't know how to make other images, but honestly that already takes too much time for me (more than 1 hour for each release), so I won't do more.
If you know how to build one, I guess you can do `vagrant up` yourself - it just won't be available on Atlas.
Anyway, if Docker 4 Windows makes Vagrant crash, you should report a bug on the Docker team - I'm not responsible if VirtualBox and Docker don't work together.
