### ISSUE TITLE
Relaunchable provisionning

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-devbox#8]
It would be great to be able to update an existing devbox with the latest script by just calling ```vagrant reload --provision```

**Comment by jdubois** [comment]
Have you tried it? I didn't know about this command, I've never used it before

**Comment by cbornet** [comment]
Yes it restarts the VM and reruns the provisionning scripts
So there are some operations that we must exclude if we have already done them or else we get duplicate entries, unnecessary downloads, etc ...

**Comment by jdubois** [comment]
OK then it would be nice to have

**Comment by jdubois** [comment]
I don't think I can make that, the Shell script is already quite complex

**Comment by cbornet** [comment]
Yes, I agree. And it's not that useful.

**Comment by zhenkyle** [comment]
Relaunchable provisioning IS a good idea. Maybe change from `shell` provisioner to `puppet` provisioner can make this idea happen?
