### ISSUE TITLE
Install KVM virtualization, docker-machine, minikube and kubectl

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-devbox#82]
Important to use kubernetes, rancher, swarm locally.
Also we are not installing virtualbox in virtualbox...

**Comment by jdubois** [comment]
We already have Docker installed, this should be enough. I really don't want to have too many things, it's really far too complex already

**Comment by cbornet** [comment]
Maybe some install scripts ready to be clicked on the Desktop could be useful ?

**Comment by pascalgrimaud** [comment]
I was thinking about that:
- remove the tools which isn't used frequently
- add scripts to install these tools easily

**Comment by jdubois** [comment]
+1000 yes let's do this

Le 6 mars 2017 7:33 PM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by PierreBesson** [comment]
+1 very good idea, much easier to test.

**Comment by pascalgrimaud** [comment]
So I propose this. Tell me if you are OK or not:
- move the tools which isn't used frequently to another folder in jhipster-devbox project: `tools`
    - python-pip + cqlsh
    - mongodb-clients
    - cloud foundry client
    - aws tools
- keep:
    - mysql-workbench
    - pgadmin3
    - toolbelt heroku
- should we keep both ? IDEA and Visual Studio Code ? I suppose Yes
- so just move the useful extensions for VSC ?

- Then, clone jhipster-devbox into the box (like for jhipster-oh-my-zsh-plugin), so the user will have the `tools` folder

**Comment by jdubois** [comment]
Yes that's the minimum for me.
For things like PGAdmin, as long as it's installed with "apt-get" the cost is very low for us. The biggest issues are the services installed with a shell script, as those take more time to install, and are much more subject to failure.

**Comment by jdubois** [comment]
I think we can close this: most of it has been done in #86 but I don't know if anybody uses it - in fact I forgot about this and never used this myself. Anyway, the current devbox looks good for most people.
