### ISSUE TITLE
Recommend installing the devbox using the 'vagrant box‘ command

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-devbox#83]
https://www.vagrantup.com/docs/cli/box.html

install:
vagrant box add jhipster/jhipster-devbox
update:
vagrant box update jhipster/jhipster-devbox

**Comment by jdubois** [comment]
Can you do a PR on the readme? I haven't looked at those, but if you say it's better...

**Comment by jdubois** [comment]
The official way is:

    vagrant init jhipster/jhipster-devbox --box-version 4.13.3
    vagrant up

(from https://app.vagrantup.com/jhipster/boxes/jhipster-devbox/versions/4.13.3 )
And this works well for everyone, so I'm closing this, unless @PierreBesson you have some other comment? I don't know about the commands you use.
