### ISSUE TITLE
Investigate building and publishing the box directly in Travis

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-devbox#84]
I'm sure this is possible and it's badly needed as building the box is way too slow.

**Comment by jdubois** [comment]
Not sure this is possible, Travis is limited to one hour for a build, and on my laptop this is already a nightmare.
Normal people should not do it anyway -> I'm just building it once and then put it on Atlas, so this should be enough. I'm the only one who should be annoyed by those builds (except when you test it, of course)

**Comment by jdubois** [comment]
Using the box on https://app.vagrantup.com/jhipster/boxes/jhipster-devbox is definitely the best way to do it. I'm testing it every time, to be sure it works well. Using "vagrant up" is slow, and you can have any kind of issue in case of network error.
