### ISSUE TITLE
While running jhipster-registry war using java -jar,not able to see the swager UI

### ISSUE THREAD

**Issue by GuruvaiahG** [jhipster/jhipster-devbox#89]
getting below screen 
??error.title_en_US??
??error.subtitle_en_US??

??error.status_en_US?? Not Found (Not Found)
??error.message_en_US?? Not Found
Other things to try:
Search localhost:8761:

localhost 8761

**Comment by pascalgrimaud** [comment]
1) you're in the jhipster-devbox project, not in the jhipster-registry
2) everything works fine for me
3) as there is not enough information to reproduce, it's not possible to help you

This ticket need to be closed.
