### ISSUE TITLE
Devbox 4.13.3 not published

### ISSUE THREAD

**Issue by dkefer** [jhipster/jhipster-devbox#90]
When I try to update the devbox to the current version, only version 4.13.2 is offered. 

When I try to pin to the version 4.13.3 using the Vagrantfile available at https://app.vagrantup.com/jhipster/boxes/jhipster-devbox/versions/4.13.3, I get the the following error message:

> Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'jhipster/jhipster-devbox' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 4.13.3
==> default: Loading metadata for box 'jhipster/jhipster-devbox'
    default: URL: https://vagrantcloud.com/jhipster/jhipster-devbox
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.
>
>Box: jhipster/jhipster-devbox
>Address: https://vagrantcloud.com/jhipster/jhipster-devbox
>Constraints: 4.13.3
>Available versions: 0.2.2, 0.2.3, 0.2.4, 2.26.1, 2.26.2, 2.27.0, 2.27.1, 2.27.2, 3.0.0, 3.1.0, 3.2.0, 3.2.1.1, 3.2.1.2, 3.2.1.3, 3.2.1.4, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.9.1, 3.10.0, 3.11.0, 3.12.0, 3.12.1, 3.12.2, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.1.0, 4.1.1, 4.2.0, 4.3.0, 4.4.0, 4.4.1, 4.5.0, 4.5.1, 4.5.2, 4.5.3, 4.5.4, 4.5.5, 4.5.6, 4.6.0, 4.6.1, 4.6.2, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.9.0, 4.10.0, 4.10.1, 4.10.2, 4.11.0, 4.11.1, 4.12.0, 4.13.0, 4.13.1, 4.13.2

**Comment by jdubois** [comment]
Oh sorry, I forgot to click on the "release" button!
This is done now :-)

**Comment by gmarziou** [comment]
It still does not work: error 404 on https://app.vagrantup.com/jhipster/boxes/jhipster-devbox/versions/4.13.3/providers/virtualbox.box

**Comment by gmarziou** [comment]
~~~sh
➜  use-dev-box vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'jhipster/jhipster-devbox' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'jhipster/jhipster-devbox'
    default: URL: https://vagrantcloud.com/jhipster/jhipster-devbox
==> default: Adding box 'jhipster/jhipster-devbox' (v4.13.3) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/jhipster/boxes/jhipster-devbox/versions/4.13.3/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
~~~

**Comment by jdubois** [comment]
I don't understand.... https://app.vagrantup.com/jhipster/boxes/jhipster-devbox/versions/4.13.3 looks OK

**Comment by jdubois** [comment]
Looks like it was deleted or something - I just reuploaded it, can you check?
(yes I got fiber connection!)

**Comment by gmarziou** [comment]
Works fine now, thanks.
