### ISSUE TITLE
How to run GUI?

### ISSUE THREAD

**Issue by jbarbaran** [jhipster/jhipster-devbox#92]
Hi,

This is probably a silly question as I'm a newbie at JHipster. 

I've just installed jhipster-devbox without problems, and connected by SSH. However, if aI understood properly you need to setup an IDE (obviously) in order to customize your JHipster application, and here is my question?

- If I use my host OS instead of Vagrant, do I have to share a folder with my host OS?

- If I prefer to do everthing inside the vagrant instance, if I can only use SSH, How am I supposed to access to GUI?

Sorry for the silly question, but I couldnt' find the solution out on the Internet,... 

Many thanks,

Javier.

**Comment by jdubois** [comment]
I guess you can connect through SSH, but obviously you won't have a GUI easily - maybe you could do some tunneling of your X connection? But that's weird.
The normal way of using this is just opening up the GUI from VirtualBox. You should see it there. I think it can also forward it using something like VNC but I've never used it.

**Comment by jbarbaran** [comment]
Many thanks for the quick response.

When I open the GUI on VirtualBox I get the following:

![imagen](https://user-images.githubusercontent.com/2361623/36060480-cd853fe4-0e4a-11e8-933a-ca3695638c59.png)

And I don't know what to do to make the GUI comes up...

There must be a way but I cannot figure out...
Could you give me a hint?

Thanks again!

**Comment by jdubois** [comment]
Maybe it didn't install properly, it should just come up automatically... Did you install it from https://app.vagrantup.com/jhipster/boxes/jhipster-devbox ? And which version did you take?

**Comment by jbarbaran** [comment]
Yes,.. I just got it running!

I did vagrant destroy, change the RAM size for the image, and I ran the image directly from VirtualBox as you said, and I can see it now..

![imagen](https://user-images.githubusercontent.com/2361623/36060545-0db7ec50-0e4c-11e8-83ce-2796e3123377.png)


Many thanks!!!

**Comment by jdubois** [comment]
Awesome!
